name: "generate-pages"

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: "read"
  pages: "write"
  id-token: "write"

jobs:
  generate-pages:
    runs-on: "ubuntu-latest"
    concurrency: "generate-pages"
    environment:
      name: "github-pages"
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Generate pages"
        run: "./generate-pages"
      - name: "Configure pages"
        uses: "actions/configure-pages@v5"
      - name: "Upload the pages artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "./pages"
      - id: "deployment"
        name: "Deploy the pages artifact"
        uses: "actions/deploy-pages@v4"
